/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { AddressMeta } from './addressMeta';

export class CreateFundingAddressResponse {
    'accountId'?: string;
    'address'?: string;
    'addressMeta'?: Array<AddressMeta>;
    'asset'?: string;
    'assignedAt'?: string;
    'name'?: string;
    'qrCodeUri'?: string;
    'receiveFee'?: string;
    'totalReceived'?: string;
    'totalUnconfirmed'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "addressMeta",
            "baseName": "address_meta",
            "type": "Array<AddressMeta>"
        },
        {
            "name": "asset",
            "baseName": "asset",
            "type": "string"
        },
        {
            "name": "assignedAt",
            "baseName": "assigned_at",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "qrCodeUri",
            "baseName": "qr_code_uri",
            "type": "string"
        },
        {
            "name": "receiveFee",
            "baseName": "receive_fee",
            "type": "string"
        },
        {
            "name": "totalReceived",
            "baseName": "total_received",
            "type": "string"
        },
        {
            "name": "totalUnconfirmed",
            "baseName": "total_unconfirmed",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateFundingAddressResponse.attributeTypeMap;
    }
}

