/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class Trade {
    'base'?: string;
    'counter'?: string;
    'feeBase'?: string;
    'feeCounter'?: string;
    'isBuy'?: boolean;
    'orderId'?: string;
    'pair'?: string;
    'price'?: string;
    'sequence'?: number;
    'timestamp'?: string;
    'type'?: Trade.TypeEnum;
    'volume'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "base",
            "baseName": "base",
            "type": "string"
        },
        {
            "name": "counter",
            "baseName": "counter",
            "type": "string"
        },
        {
            "name": "feeBase",
            "baseName": "fee_base",
            "type": "string"
        },
        {
            "name": "feeCounter",
            "baseName": "fee_counter",
            "type": "string"
        },
        {
            "name": "isBuy",
            "baseName": "is_buy",
            "type": "boolean"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "pair",
            "baseName": "pair",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string"
        },
        {
            "name": "sequence",
            "baseName": "sequence",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Trade.TypeEnum"
        },
        {
            "name": "volume",
            "baseName": "volume",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Trade.attributeTypeMap;
    }
}

export namespace Trade {
    export enum TypeEnum {
        BID = <any> 'BID',
        ASK = <any> 'ASK'
    }
}
