/**
 * Luno API
 * The Luno API provides developers with a wealth of financial information provided through the Luno platform.  Through this secure system developers can:  <ul>    <li>Create accounts for trading in cryptocurrencies</li>    <li>Access current and historic cryptocurrency market data</li>    <li>Submit trade orders and view order status</li>    <li>Buy and sell Bitcoin and Ethereum</li>    <li>Send and receive Bitcoin and Ethereum</li>    <li>Generate Bitcoin and Ethereum wallet addresses</li>  </ul>   The Luno API brings the world of Bitcoin and Ethereum to your doorstep. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { DetailFields } from './detailFields';

export class Transaction {
    'accountId'?: string;
    'available'?: string;
    'availableDelta'?: string;
    'balance'?: string;
    /**
    * Transaction amounts computed for convenience.
    */
    'balanceDelta'?: string;
    'currency'?: string;
    /**
    * Human-readable description of the transaction.
    */
    'description'?: string;
    'detailFields'?: DetailFields;
    /**
    * Human-readable label-value attributes.
    */
    'details'?: { [key: string]: string; };
    'rowIndex'?: number;
    'timestamp'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "available",
            "baseName": "available",
            "type": "string"
        },
        {
            "name": "availableDelta",
            "baseName": "available_delta",
            "type": "string"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "string"
        },
        {
            "name": "balanceDelta",
            "baseName": "balance_delta",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "detailFields",
            "baseName": "detail_fields",
            "type": "DetailFields"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "rowIndex",
            "baseName": "row_index",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Transaction.attributeTypeMap;
    }
}

